### ISSUE TITLE
when using [SwipeRefreshLayout+ListView], it throws UnsupportedOperationException

### ISSUE THREAD

**Issue by amoikevin** [zserge/anvil#106]
version:
0.5.0
code:
`swipeRefreshLayout(()->{
    size(MATCH, MATCH);
    refreshing(isRefreshing);
    skip();
    listView(()->{
    .......
    );
    skip();
});`
Error:
java.lang.UnsupportedOperationException: removeView(View) is not supported in AdapterView
                                                                        at android.widget.AdapterView.removeView(AdapterView.java:523)
                                                                        at trikita.anvil.Anvil$Mount$Iterator.start(Anvil.java:280)
                                                                        at trikita.anvil.BaseDSL.v(BaseDSL.java:74)
                                                                        at trikita.anvil.BaseDSL.v(BaseDSL.java:93)
                                                                        at trikita.anvil.support.core.ui.SupportCoreUiDSL.swipeRefreshLayout(SupportCoreUiDSL.java:104)

**Comment by amoikevin** [comment]
never mind. I made a mistake. (/ □ \)
