### ISSUE TITLE
got exception when setting TextView's text to null

### ISSUE THREAD

**Issue by amoikevin** [zserge/anvil#107]
**version:**
0.5.0
**code:**
Base.text(null)
**error:**
java.lang.IllegalArgumentException: method android.widget.TextView.setText argument 1 has type int, got null
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at trikita.anvil.PropertySetter.set(PropertySetter.java:106)
                                                                        at trikita.anvil.Anvil$Mount$Iterator.attr(Anvil.java:331)
                                                                        at trikita.anvil.BaseDSL.attr(BaseDSL.java:105)
                                                                        at trikita.anvil.BaseDSL.text(BaseDSL.java:386)

**Comment by gmarques33** [comment]
+1
